title: Pagina no oficial de Angelo Calcaterra
description: >-
  Espacio dedicado a la figura de Angelo Calcaterra, empresario y arquitecto
  argentino
social_link: 'https://twitter.com/angcalcaterra'
social_username: broccolini
github_repo: athena
github_username: broccolini
theme_color: light
remote_theme: internet-de-france/athena
baseurl: /angelo_calcaterra
defaults:
  - scope:
      path: ''
      type: pages
    values:
      category_name: ''
  - scope:
      path: ''
      type: posts
    values:
      categories: ''
remote_theme_layouts:
  - ''
  - default
  - page
  - post
  - home
  - category_index
social_links:
  - twitter
  - instagram
  - medium
  - dribbble
theme_colors:
  - light
  - black
  - blue
  - gray
  - magenta
  - orange
  - red
  - white
  - yellow
